import { cpSync, mkdtempSync, readFileSync, rmSync, utimesSync } from "node:fs";
import { readdirSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import { scanAll, buildSnapshot } from "./scan";
import { emptyCache } from "./model";

/**
 * The §6.1.7 parity gate: this port's output must deep-equal the snapshot the
 * RUST implementation produced over the same fixtures.
 *
 * `fixtures/golden-snapshot.json` is checked in and was generated by running
 * `src-tauri/src/usage`'s own scan (built standalone, without the Tauri
 * command layer) over `fixtures/home/` with every mtime pinned to T0 and the
 * clock pinned to NOW. Regenerate it from the Rust side whenever the fixture
 * corpus changes — never by pasting this port's own output, which would turn
 * the gate into a tautology.
 */

const T0 = 1_786_320_000_000; // 2026-08-10T00:00:00Z — every fixture's mtime
const NOW = 1_786_323_600_000; // T0 + 1h — the pinned scan clock

const FIXTURES = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "fixtures",
);

const temps: string[] = [];
afterEach(() => {
  for (const dir of temps.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
});

function pinTree(root: string): void {
  for (const entry of readdirSync(root)) {
    const target = path.join(root, entry);
    if (statSync(target).isDirectory()) {
      pinTree(target);
    }
    utimesSync(target, T0 / 1000, T0 / 1000);
  }
  utimesSync(root, T0 / 1000, T0 / 1000);
}

function fixtureHome(): string {
  const home = mkdtempSync(path.join(tmpdir(), "usage-parity-"));
  temps.push(home);
  // Git does not preserve mtimes, so the tree is re-pinned on every run —
  // the same pinning the golden generator applied.
  cpSync(path.join(FIXTURES, "home"), home, { recursive: true });
  pinTree(home);
  return home;
}

describe("Rust parity", () => {
  it("produces exactly the snapshot the Rust scanner produced", async () => {
    const golden = JSON.parse(
      readFileSync(path.join(FIXTURES, "golden-snapshot.json"), "utf8"),
    ) as unknown;
    const home = fixtureHome();
    const outcome = await scanAll(emptyCache(), home, NOW);
    const snapshot = buildSnapshot(outcome, NOW);
    expect(snapshot).toEqual(golden);
  });

  it("answers identically warm, without marking the cache changed", async () => {
    const home = fixtureHome();
    const cold = await scanAll(emptyCache(), home, NOW);
    expect(cold.changed).toBe(true);
    const warm = await scanAll(cold.cache, home, NOW);
    expect(warm.changed).toBe(false);
    expect(buildSnapshot(warm, NOW)).toEqual(buildSnapshot(cold, NOW));
  });
});
