// AUTO-GENERATED output goes to src-tauri/src/menu_registry.rs — this script
// itself is hand-written. Run via `npm run generate:menu` (tsx, dev/build-time
// only — never bundled into the production app).
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  ACTION_REGISTRY,
  MACOS_KEYMAP,
  type KeyBinding,
  type MenuSubmenu,
} from "../src/terminal/action-registry";
import {
  generatedFilePath,
  generatedTextMatches,
  rustfmtArguments,
} from "./generated-text";

const HEADER = `// AUTO-GENERATED by \`npm run generate:menu\` (scripts/generate-menu.ts)
// from src/terminal/action-registry.ts — do not hand-edit.
// Regenerate: npm run generate:menu

use tauri::Runtime;
`;

// event.code -> the character a Tauri/Cocoa accelerator string expects.
const CODE_TO_ACCEL: Record<string, string> = {
  BracketLeft: "[",
  BracketRight: "]",
};

function normalizeCode(code: string): string {
  if (CODE_TO_ACCEL[code]) {
    return CODE_TO_ACCEL[code];
  }
  if (code.startsWith("Key")) {
    return code.slice(3);
  }
  if (code.startsWith("Digit")) {
    return code.slice(5);
  }
  return code;
}

/** event.key -> the token a Tauri/Cocoa accelerator string expects. */
function normalizeKey(key: string): string {
  if (/^[a-z]$/.test(key)) {
    return key.toUpperCase();
  }
  if (key.length > 1) {
    return key[0].toUpperCase() + key.slice(1); // "enter" -> "Enter"
  }
  return key; // punctuation/digit as-is: "=", "-", "0", ","
}

function tokenFor(binding: KeyBinding): string {
  return "code" in binding
    ? normalizeCode(binding.code)
    : normalizeKey(binding.key);
}

/** Accelerator string for the macOS menu, or "None" if the action has no binding. */
function acceleratorFor(actionId: string): string {
  const binding = MACOS_KEYMAP.find((b) => b.action === actionId);
  if (!binding) {
    return "None";
  }
  const parts = ["CmdOrCtrl"];
  if (binding.shift) {
    parts.push("Shift");
  }
  if (binding.alt) {
    parts.push("Alt");
  }
  if (binding.ctrl) {
    parts.push("Ctrl");
  }
  parts.push(tokenFor(binding));
  return `Some("${parts.join("+")}")`;
}

function itemsFor(submenu: MenuSubmenu) {
  return ACTION_REGISTRY.filter((a) => a.menu?.submenu === submenu);
}

function buildGeneratedSubmenuFn(
  fnName: string,
  submenuLabel: string,
  submenu: MenuSubmenu,
): string {
  const items = itemsFor(submenu);
  let lastGroup: string | undefined;
  const lines: string[] = [];
  const vars: string[] = [];
  for (const item of items) {
    if (lastGroup !== undefined && item.menu?.group !== lastGroup) {
      lines.push("        .separator()");
    }
    lastGroup = item.menu?.group;
    const varName = item.id.replace(/-/g, "_");
    vars.push(
      `    let ${varName} = action_item(handle, "${item.id}", "${item.label}", ${acceleratorFor(
        item.id,
      )})?;`,
    );
    lines.push(`        .item(&${varName})`);
  }
  return `#[cfg(target_os = "macos")]
pub fn ${fnName}<R: Runtime>(
    handle: &tauri::AppHandle<R>,
) -> tauri::Result<tauri::menu::Submenu<R>> {
    use super::menu::action_item;
${vars.join("\n")}
    tauri::menu::SubmenuBuilder::new(handle, "${submenuLabel}")
${lines.join("\n")}
        .build()
}
`;
}

function buildConstTable(constName: string, submenu: MenuSubmenu): string {
  const rows = itemsFor(submenu)
    .map(
      (item) =>
        `    ("${item.id}", "${item.label}", ${acceleratorFor(item.id)}),`,
    )
    .join("\n");
  return `pub const ${constName}: &[(&str, &str, Option<&str>)] = &[\n${rows}\n];\n`;
}

const output = [
  HEADER,
  buildGeneratedSubmenuFn("build_file_menu", "File", "File"),
  buildGeneratedSubmenuFn("build_view_menu", "View", "View"),
  buildConstTable("APP_MENU_ITEMS", "App"),
  buildConstTable("EDIT_MENU_ITEMS", "Edit"),
  buildConstTable("WINDOW_MENU_ITEMS", "Window"),
].join("\n");

/**
 * Normalize to the same line-wrapping `cargo fmt` would apply, so the
 * committed file never drifts from a fresh `npm run generate:menu` just
 * because of formatting — a real content change is the only thing that
 * should show up in `git diff`/the `--check` staleness guard below.
 */
function formatInPlace(...paths: string[]): void {
  try {
    execFileSync("rustfmt", rustfmtArguments(...paths), { stdio: "inherit" });
  } catch (err) {
    console.warn(
      "generate-menu: rustfmt not found or failed — the file was written " +
        "unformatted. Run `cargo fmt` manually before committing.",
      err,
    );
  }
}

const outPath = new URL("../src-tauri/src/menu_registry.rs", import.meta.url);

if (process.argv.includes("--check")) {
  // Staleness guard (Task 7): regenerate into a scratch file — NEVER touch
  // the committed one — format it the same way, then compare bytes. This is
  // an npm-only, opt-in check (predev/prebuild below always overwrite and
  // fix drift automatically; this is for CI/manual verification catching
  // "action-registry.ts changed but menu_registry.rs wasn't regenerated
  // before commit"). It doesn't run from `cargo check`/`cargo test` — those
  // build straight from the already-committed file, exactly as before.
  const scratchDir = mkdtempSync(join(tmpdir(), "generate-menu-check-"));
  const scratchPath = join(scratchDir, "menu_registry.rs");
  const committedScratchPath = join(
    scratchDir,
    "committed_menu_registry.rs",
  );
  try {
    writeFileSync(scratchPath, output);
    writeFileSync(committedScratchPath, readFileSync(outPath, "utf8"));
    formatInPlace(scratchPath, committedScratchPath);
    const fresh = readFileSync(scratchPath, "utf8");
    const committed = readFileSync(committedScratchPath, "utf8");
    if (!generatedTextMatches(fresh, committed)) {
      console.error(
        "generate-menu --check: src-tauri/src/menu_registry.rs is stale — " +
          "it doesn't match what src/terminal/action-registry.ts generates " +
          "right now. Run `npm run generate:menu` and commit the result.",
      );
      process.exit(1);
    }
  } finally {
    rmSync(scratchDir, { recursive: true, force: true });
  }
} else {
  writeFileSync(outPath, output);
  formatInPlace(generatedFilePath(outPath));
}
