// AUTO-GENERATED by `npm run generate:menu` (scripts/generate-menu.ts)
// from src/terminal/action-registry.ts — do not hand-edit.
// Regenerate: npm run generate:menu

#[cfg(target_os = "macos")]
use tauri::Runtime;

#[cfg(target_os = "macos")]
pub fn build_file_menu<R: Runtime>(
    handle: &tauri::AppHandle<R>,
) -> tauri::Result<tauri::menu::Submenu<R>> {
    use super::menu::action_item;
    let new_tab = action_item(handle, "new-tab", "New Tab", Some("CmdOrCtrl+T"))?;
    let reopen_tab = action_item(
        handle,
        "reopen-tab",
        "Reopen Closed Tab",
        Some("CmdOrCtrl+Shift+T"),
    )?;
    let new_preset = action_item(
        handle,
        "new-preset",
        "New Layout Preset…",
        Some("CmdOrCtrl+Shift+N"),
    )?;
    let save_preset = action_item(
        handle,
        "save-preset",
        "Save Layout as Preset…",
        Some("CmdOrCtrl+Shift+S"),
    )?;
    let close_pane = action_item(handle, "close-pane", "Close Pane", Some("CmdOrCtrl+W"))?;
    let close_tab = action_item(handle, "close-tab", "Close Tab", Some("CmdOrCtrl+Shift+W"))?;
    tauri::menu::SubmenuBuilder::new(handle, "File")
        .item(&new_tab)
        .item(&reopen_tab)
        .separator()
        .item(&new_preset)
        .item(&save_preset)
        .separator()
        .item(&close_pane)
        .item(&close_tab)
        .build()
}

#[cfg(target_os = "macos")]
pub fn build_view_menu<R: Runtime>(
    handle: &tauri::AppHandle<R>,
) -> tauri::Result<tauri::menu::Submenu<R>> {
    use super::menu::action_item;
    let split_row = action_item(handle, "split-row", "Split Vertically", Some("CmdOrCtrl+D"))?;
    let split_column = action_item(
        handle,
        "split-column",
        "Split Horizontally",
        Some("CmdOrCtrl+Shift+D"),
    )?;
    let toggle_zoom_pane = action_item(
        handle,
        "toggle-zoom-pane",
        "Zoom Pane",
        Some("CmdOrCtrl+Shift+Enter"),
    )?;
    let toggle_expand = action_item(handle, "toggle-expand", "Focus Expand", Some("CmdOrCtrl+E"))?;
    let zoom_in = action_item(handle, "zoom-in", "Increase Font Size", Some("CmdOrCtrl+="))?;
    let zoom_out = action_item(
        handle,
        "zoom-out",
        "Decrease Font Size",
        Some("CmdOrCtrl+-"),
    )?;
    let zoom_reset = action_item(handle, "zoom-reset", "Actual Size", Some("CmdOrCtrl+0"))?;
    let focus_next_attention = action_item(
        handle,
        "focus-next-attention",
        "Next Agent Needing Attention",
        Some("CmdOrCtrl+Shift+A"),
    )?;
    let toggle_prompts = action_item(
        handle,
        "toggle-prompts",
        "Prompts…",
        Some("CmdOrCtrl+Shift+P"),
    )?;
    tauri::menu::SubmenuBuilder::new(handle, "View")
        .item(&split_row)
        .item(&split_column)
        .separator()
        .item(&toggle_zoom_pane)
        .item(&toggle_expand)
        .separator()
        .item(&zoom_in)
        .item(&zoom_out)
        .item(&zoom_reset)
        .separator()
        .item(&focus_next_attention)
        .separator()
        .item(&toggle_prompts)
        .build()
}

pub const APP_MENU_ITEMS: &[(&str, &str, Option<&str>)] = &[
    ("check-for-updates", "Check for Updates…", None),
    ("open-release-notes", "Release Notes…", None),
    ("toggle-settings", "Settings…", Some("CmdOrCtrl+,")),
];

pub const EDIT_MENU_ITEMS: &[(&str, &str, Option<&str>)] = &[
    ("find", "Find…", Some("CmdOrCtrl+F")),
    ("find-next", "Find Next", Some("CmdOrCtrl+G")),
    ("find-previous", "Find Previous", Some("CmdOrCtrl+Shift+G")),
    ("clear-buffer", "Clear Buffer", Some("CmdOrCtrl+K")),
    (
        "copy-cwd",
        "Copy Working Directory",
        Some("CmdOrCtrl+Shift+C"),
    ),
];

pub const WINDOW_MENU_ITEMS: &[(&str, &str, Option<&str>)] = &[];
